openapi: 3.0.2
servers: []
info:
  version: 2.0.0
  title: GA4GH Beacon API Specification - Individuals Endpoints
  description: TBD
  contact:
    email: beacon@ga4gh.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /individuals:
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/includeResultsetResponses'
        - $ref: '#/components/parameters/filters'
      description: Get a list of individuals
      operationId: getIndividuals
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
    post:
      description: Get a list of example entries
      operationId: postIndividualsRequest
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/requests/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
  /individuals/{id}:
    parameters:
      - $ref: '#/components/parameters/entryId'
    get:
      description: Get details about one individual, identified by its (unique) 'id'
      operationId: getOneIndividual
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
    post:
      description: Get details about one Individual, identified by its (unique) 'id'
      operationId: postOneIndividual
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/requests/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
  /individuals/{id}/g_variants:
    parameters:
      - $ref: '#/components/parameters/entryId'
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
      description: Get the genomic variants list from one individual, identified by
        its (unique) 'id'
      operationId: getOneIndividualGenomicVariants
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
    post:
      description: Get the genomic variants list from one individual, identified by
        its (unique) 'id'
      operationId: postOneIndividualGenomicVariants
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/requests/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
  /individuals/{id}/biosamples:
    parameters:
      - $ref: '#/components/parameters/entryId'
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
      description: Get the biosamples list from one individual, identified by its
        (unique) 'id'
      operationId: getOneIndividualBiosamples
      tags:
        - GET Endpoints
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
    post:
      description: Get the biosamples list from one individual, identified by its
        (unique) 'id'
      operationId: postOneIndividualBiosamples
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/requests/beaconRequestBody.json
        required: true
      responses:
        '200':
          $ref: '#/components/responses/ResultsOKResponse'
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
  /individuals/filtering_terms:
    get:
      parameters:
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
      description: Get the list of filtering terms that could be used with individuals.
      operationId: getIndividualsFilteringTerms
      tags:
        - GET Endpoints
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconFilteringTermsResponse.json
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
    post:
      description: Get the list of filtering terms that could be used with individuals.
      operationId: postIndividualsFilteringTerms
      tags:
        - POST Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/requests/beaconRequestBody.json
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconFilteringTermsResponse.json
        default:
          description: An unsuccessful operation
          $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconErrorResponse.json
components:
  responses:
    ResultsOKResponse:
      description: Successful operation.
      content:
        application/json:
          schema:
            oneOf:
              - $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconBooleanResponse.json
              - $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconCountResponse.json
              - $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/responses/beaconResultsetsResponse.json
  parameters:
    requestedSchema:
      name: requestedSchema
      description: Schema to be used to format the `result` field in the response.
        The response will use Beacon format.
      in: query
      required: false
      schema:
        type: string
      example: ga4gh-service-info-v1.0
    skip:
      name: skip
      in: query
      schema:
        $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/common/beaconCommonComponents.json#/definitions/Skip
    limit:
      name: limit
      in: query
      schema:
        $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/common/beaconCommonComponents.json#/definitions/Limit
    includeResultsetResponses:
      $ref: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/framework/json/common/beaconCommonComponents.json#/definitions/IncludeResultsetResponses
    entryId:
      name: id
      in: path
      required: true
      schema:
        type: string
    filters:
      name: filters
      in: query
      schema:
        type: array
        items:
          type: string
        examples:
          -   - NCIT:C20197
