$schema: https://json-schema.org/draft/2020-12/schema
type: object
description: >-
  The `beaconConfigurationResponse` returns information about configuration
  parameters of a given beacon instance such as maturity or security attributes
  or supported entry types. It is directed towards Beacon clients like web pages
  or network aggregators.
properties:
  meta:
    description: >-
      Information about the response that could be relevant for the Beacon
      client in order to interpret the results.
    $ref: ./sections/beaconInformationalResponseMeta.yaml
  response:
    description: >-
      Returning the Beacon configuration.
    $ref: ../configuration/beaconConfigurationSchema.yaml
required:
  - meta
  - response
additionalProperties: true
